name = "test_PETSc_jll"
uuid = "6087adde-dd95-4294-8545-a84a118ed386"
authors = ["Boris Kaus <kaus@uni-mainz.de>"]
version = "0.1.0"

[deps]
PETSc_jll = "8fa3689e-f0b9-5420-9873-adf6ccf46f2d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6"
PETSc_jll = "3.18"

